config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'resume' => 'static_pages#resume'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
	end

	def resume
		send_file("#{Rails.root}/public/OConnor, Ryan_Resume_Nov15.pdf", type: "application/pdf")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div id="contact">
    <div id="social_media" class="row">
        <div class="small-2 medium-2 columns">
          <%= link_to image_tag("Social_1.png", class: 'logo_images', alt: 'LinkedIn'), "https://www.linkedin.com/pub/ryan-o-connor/90/abb/a58" %>
        </div>

        <div class="small-2 medium-2 columns">
          <%= link_to image_tag('Social_2.png', class: 'logo_images', id: "twitter", alt: 'Twitter'), "https://twitter.com/OC_Ryn/" %>
        </div>

        <div class="small-2 medium-2 columns">
          <%= link_to image_tag('GitHub.png', class: 'logo_images', alt: 'GitHub Logo'), "https://github.com/charle692/" %>
        </div>

        <div class="small-2 medium-2 columns">
          <%= mail_to 'charle692@gmail.com', image_tag('mail.png', class: 'logo_images', id: 'mail', alt: 'Email'), encode: "hex" %>
        </div>

        <div class="small-2 small-pull-2 medium-2 columns">
          <span><%= link_to 'CV', resume_path %></span>
        </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="tab-bar">
  <section class="right">
    <a class="right-off-canvas-toggle menu-icon"><span></span></a>
  </section>
</nav>

<aside class="right-off-canvas-menu">
  <ul class="off-canvas-list">
    <li class="text-center"><label>Navigation</label></li>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', root_path+'#about'%></li>
    <li><%= link_to 'Education', root_path+'#education'%></li>
    <li><%= link_to 'Experience', root_path+'#experience'%></li>
    <li><%= link_to 'Skills', root_path+'#skills'%></li>
    <li><%= link_to 'Projects', root_path+'#projects'%></li>
    <li><%= link_to 'Contact', root_path+'#contact'%></li>
  </ul>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Hi, my name is Ryan O'Connor and I have
     just completed my 3rd year of software engineering at the University of
      Ottawa. I was first introduced to coding during my Visual Basic
       programming class back in high school. Ever since then I haven't
        looked back." />
    <title><%= content_for?(:title) ? yield(:title) : "Ryan O'Connor" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <link href='//fonts.googleapis.com/css?family=Fira+Sans' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <div class="off-canvas-wrap" data-offcanvas>
      <div class="inner-wrap">
        <%= render 'layouts/header' %>
        <%= link_to '', '', class: "exit-off-canvas" %>
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
    <%= javascript_include_tag "application", async: true %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-62101935-1', 'auto');
      ga('send', 'pageview');
    </script>
  </body>
</html>

app/views/static_pages/index.html.erb
<div id="about">
	<div class="row">
		<div class="small-8 small-centered medium-uncentered medium-4 columns about">
			<%= image_tag('profile_picture.png', id: "profile_picture", alt: 'Ryan O\'Connor') %>
		</div>

		<div class="small-12 medium-8 columns">
			<div class="medium-pull-3 columns">
				<h2 id="about_header" class="about text-center">About Me</h2>
			</div>

			<p class="about_text">
				Hi, my name is Ryan O'Connor and I am currently in my 4th year of software engineering at the University of Ottawa. I was first introduced to coding during my Visual Basic programming class back in high school. Ever since then I haven't looked back. After discovering how rewarding it is to solve problems using code, I knew that's what I wanted to do for the rest of my life.
			</p>
			<p class="about_text">
				I am currently VP Academic of the <%= link_to "Software Engineering Student Association", "http://uottawa-sesa.ca" %> where I help organize weekly Ruby on Rails tutorials, study sessions, and coding events for students. When I'm taking a break from programming and helping others, I like to go skating, snowmobiling, or enjoying my time out on the water.
			</p>
		</div>
	</div>
</div>

<div id="education">
	<div class="subtitle">
		<div class="row">
			<h2 class="text-center">Education</h2>
		</div>
	</div>

	<div class="row">
		<div class="small-12 medium-4 columns">
			<h3 class="subheaders">University of Ottawa</h3>
			<p class="date">September 2012 - Current</p>
		</div>

		<div class="small-12 medium-8 columns">
			<strong>BASc in Software Engineering</strong>
			<p>
				My studies at the University of Ottawa have allowed me to develop strong design skills by using requirements engineering techniques, analysis level diagrams, and design level diagrams. I've also learned how to translate requirements and diagrams into quality software. Java has been used as the main programming language for learning, however I've also had the opportunity to use HTML, CSS, SQL, and Ruby.
			</p>
		</div>
	</div>
</div>

<div id="experience">
	<div class="subtitle">
		<div class="row">
			<h2 class="text-center">Experience</h2>
		</div>
	</div>

	<div class="row">
		<div class="small-12 medium-4 columns">
			<h3 class="subheaders">BiteSite</h3>
			<p class="date">May 2015 - Current</p>
		</div>

		<div class="small-12 medium-8 columns">
			<strong>Junior Software Developer</strong>
			<p>
				<%= link_to 'BiteSite', 'http://bitesite.ca' %> is a small software development firm based out of Ottawa, Ontario where we develop full stack web applications. While working at BiteSite, I've developed a strong understanding of Ruby on Rails, RSpec through TDD, Git, and a basic understanding of JavaScript. At BiteSite, I had the opportunity to build software both independently, and with a team using agile processes.
			</p>
		</div>
	</div>

	<div class="row experience">
		<div class="small-12 medium-4 columns">
			<h3 class="subheaders">Bell Canada</h3>
			<p class="date">June 2014 - August 2014</p>
			<p class="date">May 2015 - August 2015</p>
		</div>

		<div class="small-12 medium-8 columns">
			<strong>VoIP Manager - Service Assurance and Development</strong>
			<p>
				At Bell Canada I provided quality assurance for Bell's VoIP platform. I helped customers with validation testing and verified that their results were as expected by analyzing SIP traces using Wireshark. I was involved with testing for new platform releases and helped with diagnosing system failures. During my time working at Bell Canada I implemented call forwarding on FreeSwitch for internal release testing.
			</p>
		</div>
	</div>

	<div class="row experience">
		<div class="small-12 medium-4 columns">
			<h3 class="subheaders">SigmaPoint Technologies</h3>
			<p class="date">May 2013 - August 2013</p>
		</div>

		<div class="small-12 medium-8 columns">
			<strong>Kontron Mechanic</strong>
			<p>
				SigmaPoint Technologies is an electronics manufacturer where I worked as a Kontron mechanic. I assembled, diagnosed, and repaired CompactPCI boards and server boards. I worked under the Toyota Production System, used to provide quality products in a fast and efficient manner while reducing waste.
			</p>
		</div>
	</div>
</div>

<div id="skills">
	<div class="subtitle">
		<div class="row">
			<h2 class="text-center">Skills</h2>
		</div>
	</div>

	<div class="row">
		<div class="small-12 medium-6 medium-centered columns">
			<table>
				<tr>
					<td class="column1"><%= link_to image_tag('Java.png', class: 'skill_logo', id: 'Java', alt: 'Java'), "https://www.java.com/en/" %></td>
					<td class="column2">Java</td>
					<td class="column3"><%= link_to image_tag('terminal.png', class: 'skill_logo', id: 'Terminal', alt: 'Terminal')%></td>
					<td class="column4">Terminal</td>
				</tr>

				<tr>
					<td><%= link_to image_tag('HTML5.png', class: 'skill_logo', id: 'HTML', alt: 'HTML'), "http://www.w3.org" %></td>
					<td class="column2">HTML</td>

					<td class="column3"><%= image_tag 'Hardware.png', class: 'skill_logo', id: 'Hardware', alt: 'Hardware' %></td>
					<td class="column4">Hardware</td>
				</tr>

				<tr>
					<td><%= link_to image_tag('css.png', class: 'skill_logo', id: 'CSS', alt: 'CSS'), "http://www.w3.org" %></td>
					<td class="column2">CSS</td>

					<td class="column3"><%= link_to image_tag('Git.png', class: 'skill_logo', id: 'Git', alt: 'Git'), "http://git-scm.com"%></td>
					<td class="column4">Git</td>
				</tr>

				<tr>
					<td><%= link_to image_tag('ruby.png', class: 'skill_logo', id: 'Ruby', alt: 'Ruby'), "https://www.ruby-lang.org/en/" %></td>
					<td class="column2">Ruby</td>

					<td class="column3"><%= link_to image_tag('android-sdk.png', class: 'skill_logo', id: 'Android-Sdk', alt: 'Android SDK'), "http://developer.android.com/index.html"%></td>
					<td class="column4">Android SDK</td>
				</tr>

				<tr>
					<td><%= link_to image_tag('PostgreSQL.png', class: 'skill_logo', id: 'PostgreSQL', alt: 'PostgreSQL'), "http://www.postgresql.org" %></td>
					<td class="column2">PostgreSQL</td>

					<td class="column3"><%= link_to image_tag('linux.png', class: 'skill_logo', id: 'Linux', alt: 'Linux Tux'), "http://www.linuxfoundation.org"%></td>
					<td class="column4">Linux</td>
				</tr>

				<tr>
					<td><%= link_to image_tag('RoR.png', class: 'skill_logo', id: 'RoR', alt: 'Ruby on Rails'), "http://rubyonrails.org" %></td>
					<td class="column2">Ruby on Rails</td>

					<td class="column3"><%= link_to image_tag('bootstrap.png', class: 'skill_logo', id: 'Bootstrap', alt: 'Bootstrap'), "http://getbootstrap.com"%></td>
					<td class="column4">Bootstrap</td>
				</tr>

				<tr>
					<td><%= link_to image_tag('foundation.png', class: 'skill_logo', id: 'Foundation', alt: 'Foundation'), "http://foundation.zurb.com"%></td>
					<td class="column2">Foundation</td>
				</tr>
			</table>
		</div>
	</div>
</div>

<div id="projects">
	<div class="subtitle">
		<div class="row">
			<h2 class="text-center">Projects</h2>
		</div>
	</div>

	<div class="row">
		<div class="small-12 medium-6 columns">
			<h3 class="subheaders project_header">
				<%= link_to 'Book Store', 'https://github.com/charle692/bookstore' %>
			</h3>
			<p>
				Book Store is web application that I am building for a friend using Ruby on Rails. As the name suggests, this project is an e-commerce store used to sell Czech books. This project allowed me to experiment while gathering a basic understanding of Ruby on Rails.
			</p>
		</div>

		<div class="small-12 medium-6 columns">
			<%= link_to image_tag('book_store.jpg', class: 'project_image', id: 'boostore', alt: 'Book store home screen'), 'https://github.com/charle692/bookstore' %>
		</div>
	</div>

	<div class="project_container row">
		<div class="medium-6 medium-push-6 small-12 columns">
			<h3 class="subheaders project_header">
				<%= link_to 'Property Rental System', 'https://bearybestrentals.herokuapp.com' %>
			</h3>
			<p>
				Built using Ruby on Rails and Foundation 5, this application was build as a final project for Software Design and Architecture in collaboration with <%= link_to "Craig Bryan", "http://www.craigbryan.me/" %>, and <%= link_to "Katarina Drobnjakovic", 'http://katarina.rocks/' %>. Beary Best Rentals is a property rental system. It allows customers to search for property rentals provided by other Beary Best Rental users.
			</p>
		</div>

		<div class="medium-6 medium-pull-6 small-12 columns">
			<%= link_to image_tag('BearyBestRentals.jpg', class: 'project_image', id: 'beary', alt: 'Beary Best Rentals'), "https://bearybestrentals.herokuapp.com" %>
		</div>
	</div>

	<div class="project_container row">
		<div class="small-12 medium-6 columns">
			<h3 class="subheaders project_header">
				<%= link_to 'Binary Converter', 'https://play.google.com/store/apps/details?id=com.Charle692.BinaryConverter' %>
			</h3>
			<p>
				Binary Converter is a simple Android application I built during the summer of 2014. This was my first experience building a mobile application. While building the application I learned about layouts, Android Debug Bridge (ABD), and the basics of Android development.
			</p>
		</div>

		<div class="small-12 medium-6 columns">
			<%= link_to image_tag('Binary_converter.png', class: 'project_image', id: 'binary_screens', alt: 'Binary Converter'), "https://play.google.com/store/apps/details?id=com.Charle692.BinaryConverter" %>
		</div>
	</div>
</div>